# Manifold Example Configuration

# Manifold Host
host: 'localhost'
port: 8080

# Manifold storage path: models, database files, etc
data_path: '~/.manifold'

# Jaeger endpoint for tracing
jaeger_host: 'localhost:16686'

# Database Configuration (PGVector)
database:
  connection_string: "postgres://pgadmin:yourpassword@localhost:5432/manifold?sslmode=disable"  # REPLACE with your actual credentials

# Embeddings API Configuration
embeddings:
  host: "http://localhost:8081/v1/embeddings" #  Replace with your actual embeddings API endpoint
  api_key: "your_embeddings_api_key"      #  Replace with your actual embeddings API key, not used for local embeddings