# Manifold Example Configuration

# Manifold Host
host: 'localhost'
port: 8080

# Manifold storage path: models, database files, etc
data_path: '~/.manifold'

# Database Configuration (PGVector)
database:
  connection_string: "postgres://pgadmin:yourpassword@localhost:5432/manifold?sslmode=disable"  # REPLACE with your actual credentials

# HuggingFace Token
hf_token: "..." 

# Anthropic API token
anthropic_key: "..."

# Default Completions Configuration - any openai api compatible backend - llama.cpp (llama-server), vllm, mlx_lm.server, etc
completions:
  default_host: "<my_openai_api_compatible_server>/v1/chat/completions"
  # OpenAI API compatible API key, not required for local servers unless configured on that server
  api_key: "my_api_key"

# Embeddings API Configuration
# Manifold is tested with https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF
embeddings:
  host: "<my_openai_api_compatible_server>/v1/embeddings"
  # OpenAI API compatible API key, not required for local servers unless configured on that server
  api_key: "your_embeddings_api_key"
  dimensions: 768 # Size of embedding dimensions
  embed_prefix: "search_document: "
  search_prefix: "search_query: "

# Reranker llama.cpp endpoint
reranker:
  host: "<my llama.cpp or other /v1/rerank endpoint>"
