// Code generated by "stringer -type=Language ./internal/documents/"; DO NOT EDIT.

package documents

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Go-1]
	_ = x[Python-2]
	_ = x[JavaScript-3]
	_ = x[TypeScript-4]
	_ = x[Java-5]
	_ = x[CSharp-6]
	_ = x[Rust-7]
	_ = x[Cpp-8]
	_ = x[C-9]
	_ = x[Markdown-10]
	_ = x[JSON-11]
	_ = x[YAML-12]
	_ = x[XML-13]
	_ = x[HTML-14]
	_ = x[CSS-15]
	_ = x[SQL-16]
	_ = x[Shell-17]
	_ = x[Plain-18]
}

const _Language_name = "UnknownGoPythonJavaScriptTypeScriptJavaCSharpRustCppCMarkdownJSONYAMLXMLHTMLCSSSQLShellPlain"

var _Language_index = [...]uint8{0, 7, 9, 15, 25, 35, 39, 45, 49, 52, 53, 61, 65, 69, 72, 76, 79, 82, 87, 92}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
