export type ChatRole = "user" | "assistant" | "tool" | "system" | "status";

export type ChatAttachmentKind = "image" | "text";

export interface ChatAttachment {
  id: string;
  kind: ChatAttachmentKind;
  name: string;
  size?: number;
  mime?: string;
  // For images we store a data URL so thumbnails persist across reloads
  previewUrl?: string;
  // Optional relative or full path on disk (when generated by the agent)
  path?: string;
  // For text attachments, optionally cache the text content for display/debug
  text?: string;
}

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: string;
  streaming?: boolean;
  title?: string;
  error?: string;
  // Deprecated: thought summaries are now streamed into the Active Specialist panel.
  // Kept for backward compatibility with persisted sessions.
  thoughtSummary?: string;
  thoughtSummaryFading?: boolean;
  toolArgs?: string;
  audioUrl?: string;
  audioFilePath?: string;
  attachments?: ChatAttachment[];
  agent?: string;
  agentName?: string;
  agentModel?: string;
  model?: string;
}

export interface ChatSessionMeta {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  lastMessagePreview?: string;
  messageCount?: number;
  model?: string;
}

export interface AgentTraceEntry {
  id: string;
  type: "message" | "tool" | "error";
  role?: ChatRole;
  title?: string;
  content?: string;
  args?: string;
  data?: string;
  createdAt: string;
}

export interface AgentThread {
  callId: string;
  parentCallId?: string;
  agent?: string;
  model?: string;
  prompt?: string;
  depth: number;
  status: "running" | "done" | "error";
  content: string;
  entries: AgentTraceEntry[];
  startedAt: string;
  finishedAt?: string;
  error?: string;
}
