export type ChatRole = "user" | "assistant" | "tool" | "system" | "status";

export type ChatAttachmentKind = "image" | "text";

export interface ChatAttachment {
  id: string;
  kind: ChatAttachmentKind;
  name: string;
  size?: number;
  mime?: string;
  // For images we store a data URL so thumbnails persist across reloads
  previewUrl?: string;
  // Optional relative or full path on disk (when generated by the agent)
  path?: string;
  // For text attachments, optionally cache the text content for display/debug
  text?: string;
}

export interface ChatInputRequestChoice {
  id: string;
  label: string;
  description?: string;
}

export interface ChatInputRequest {
  id: string;
  question: string;
  reason?: string;
  choices: ChatInputRequestChoice[];
  allowFreeText: boolean;
  multiple: boolean;
  agent?: string;
  team?: string;
  model?: string;
  callId?: string;
  parentCallId?: string;
  depth?: number;
  status: "pending" | "answered" | "cancelled" | "error";
  answer?: string;
  choiceIds?: string[];
  error?: string;
  createdAt: string;
  answeredAt?: string;
}

export interface ChatMemoryContextLane {
  enabled?: boolean;
  returned?: boolean;
  timedOut?: boolean;
  error?: string;
  durationMs?: number;
  items?: number;
  tokens?: number;
}

export interface ChatMemoryContext {
  text: string;
  tokenEstimate?: number;
  truncated?: boolean;
  durationMs?: number;
  lanes?: Record<string, ChatMemoryContextLane>;
}

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: string;
  streaming?: boolean;
  title?: string;
  error?: string;
  // Deprecated: thought summaries are now streamed into the Active Specialist panel.
  // Kept for backward compatibility with persisted sessions.
  thoughtSummary?: string;
  thoughtSummaryFading?: boolean;
  toolArgs?: string;
  audioUrl?: string;
  audioFilePath?: string;
  attachments?: ChatAttachment[];
  agent?: string;
  agentName?: string;
  agentModel?: string;
  model?: string;
  activityToolTitle?: string;
  activityThoughtSummary?: string;
  memoryContext?: ChatMemoryContext;
  inputRequests?: ChatInputRequest[];
}

export interface ChatSessionMeta {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  lastMessagePreview?: string;
  messageCount?: number;
  model?: string;
  projectId?: string;
  memoryEnabled?: boolean;
  evolvingMemoryEnabled?: boolean;
  beliefMemoryEnabled?: boolean;
}

export interface AgentTraceEntry {
  id: string;
  type: "message" | "tool" | "error" | "input_request";
  role?: ChatRole;
  title?: string;
  content?: string;
  args?: string;
  data?: string;
  createdAt: string;
}

export interface AgentThread {
  callId: string;
  assistantMessageId?: string;
  parentCallId?: string;
  agent?: string;
  team?: string;
  model?: string;
  prompt?: string;
  depth: number;
  status: "running" | "done" | "error";
  content: string;
  entries: AgentTraceEntry[];
  thoughtSummaries: string[];
  startedAt: string;
  finishedAt?: string;
  error?: string;
}

export interface SpecialistActivityEntry {
  id: string;
  type: string;
  title?: string;
  content?: string;
  args?: string;
  data?: string;
  createdAt: string;
}

export interface SpecialistActivityRecord {
  id: string;
  sessionId: string;
  userId?: number;
  runId?: string;
  assistantMessageId?: string;
  callId: string;
  parentCallId?: string;
  agent: string;
  team?: string;
  model?: string;
  prompt?: string;
  depth: number;
  status: "running" | "done" | "error" | "idle";
  content?: string;
  entries?: SpecialistActivityEntry[];
  thoughtSummaries?: string[];
  error?: string;
  startedAt: string;
  updatedAt: string;
  finishedAt?: string;
}
